version: '3.8'

# Docker Compose configuration for local development
# Only runs PostgreSQL and Keycloak in containers
# Backend and Frontend run locally via IDE

services:
  postgres:
    image: postgres:15
    container_name: expense-tracker-db-local
    environment:
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --data-checksums"
    ports:
      - "5432:5432"
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
      - ./docker/postgres/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - expense-tracker-local-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d expense_tracker"]
      interval: 30s
      timeout: 10s
      retries: 3

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    container_name: expense-tracker-keycloak-local
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      # Important: Configure for external access
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8081
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./docker/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./docker/keycloak/themes:/opt/keycloak/themes
    networks:
      - expense-tracker-local-network
    restart: unless-stopped
    command: start-dev --import-realm
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/realms/expense-tracker || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_local_data:
    driver: local

networks:
  expense-tracker-local-network:
    driver: bridge