export enum ExpenseCategory {
  FOOD = 'FOOD',
  TRANSPORTATION = 'TRANSPORTATION',
  ENTERTAINMENT = 'ENTERTAINMENT',
  HEALTHCARE = 'HEALTHCARE',
  SHOPPING = 'SHOPPING',
  BILLS = 'BILLS',
  OTHER = 'OTHER',
}
